/**
 * Authors:
 * Julian David Meneses
 * Santiago Escandon
 * Miguel Angel Calambas
 */
package com.unicauca.edu.co.BasicCrud.Domain;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.List;
import java.util.UUID;

@Getter
@Setter
@AllArgsConstructor
@Entity
@Table(name= "BUYENTITY")
public class BuyEntity {

    /**
     * ID of the table
     * Autogenerated
     */
    @Id
    @Column(name = "id_buy")
    private String idBuy;

    /**
     * Relation on to many with ComicToBuyEntity
     * List of comics of the buy
     */
    @OneToMany(mappedBy = "buyEntity")
    private List<ComicToBuyEntity> listComicsToBuy;

    /**
     * Name of the client
     */
    @Column(name = "name_client")
    private String nameClient;

    /**
     * Mean of the payment - Metodo pago
     */
    @Column(name = "means_payment")
    private String meansPayment;

    /**
     * Date of the buy
     */
    @Column(name = "buy_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date buyhDate;

    // Constructor without args (required by JPA)
    public BuyEntity() {
    }

    @PrePersist
    public void generateId() {
        this.idBuy = UUID.randomUUID().toString();
    }
}
