package com.unicauca.edu.co.BasicCrud.Domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.List;

@Getter
@Setter
@Entity
@Table(name= "COMICENTITY")
public class ComicEntity {

    /**
     * ID of the comic
     * Autogenerated
     */
    @Id
    @Column(name = "id_comic")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String idComic;

    /**
     * Name of the comic
     */
    @Column(name = "name_comic")
    private String nameComic;

    /**
     * Edition of the comic
     */
    @Column(name = "edition_comic")
    private int editionComic;

    /**
     * Description of the comic
     */
    @Column(name = "description_comic")
    private String descriptionComic;

    /**
     * publish date of the comic
     */
    @Column(name = "publish_date")
    @Temporal(TemporalType.DATE)
    private Date publishDate;

    /**
     * Actual price of the comic
     */
    @Column(name = "price")
    private float price;

    /**
     * Relation with comic ComicToBuyEntity
     * It ave all the buy where the comic are relational
     */
    @OneToMany(mappedBy = "comicEntity")
    private List<ComicToBuyEntity> comicsToBuy;

    public ComicEntity(){

    }
}
